# Generated by Django 5.0.1 on 2026-02-05 11:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, help_text='Unique employee identifier (e.g., EMP001)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full name of the employee', max_length=100)),
                ('email', models.EmailField(help_text='Email address of the employee', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('department', models.CharField(choices=[('Engineering', 'Engineering'), ('Marketing', 'Marketing'), ('Human Resources', 'Human Resources'), ('Sales', 'Sales'), ('Finance', 'Finance'), ('Operations', 'Operations')], help_text='Department where the employee works', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee_id'], name='employees_e_employe_514cc5_idx'), models.Index(fields=['email'], name='employees_e_email_8f5bbc_idx'), models.Index(fields=['department'], name='employees_e_departm_e28f46_idx')],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date of attendance')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], help_text='Attendance status (Present/Absent)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='The employee this attendance record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='employees_a_date_b8bb7b_idx'), models.Index(fields=['employee', 'date'], name='employees_a_employe_030d17_idx'), models.Index(fields=['status'], name='employees_a_status_8f0e4b_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
